### ISSUE TITLE
can't build under Ubuntu 16

### ISSUE THREAD

**Issue by dvescovi1** [Leeway213/WinIoTBoot#1]
I was attempting to rebuild the EFI to support win10 core.
I followed the instructions at:https://github.com/Leeway213/WinIoTBoot

I am running under Ubuntu 16 (64bit) as the Windows build is not supported yet.

After executing the ./build.sh script in the SunxiPlatformPkg directory and answering the target questions it failed because the "C" directory in the base tools source folder is not present. I copied the "C" folder from the edk2 master repo and it rebuild tools now on launch of same script but now I get the following error:

Build start time: 09:25:01, Jan.07 2017

WORKSPACE        = /home/david/edk2
ECP_SOURCE       = /home/david/edk2/EdkCompatibilityPkg
EDK_SOURCE       = /home/david/edk2/EdkCompatibilityPkg
EFI_SOURCE       = /home/david/edk2/EdkCompatibilityPkg
EDK_TOOLS_PATH   = /home/david/edk2/BaseTools

Architecture(s)  = ARM
Build target     = RELEASE
Toolchain        = ARMLINUXGCC

Active Platform          = /home/david/edk2/SunxiPlatformPkg/sun50iw1p1Pkg/sun50iw1p1Pkg.dsc
Flash Image Definition   = /home/david/edk2/SunxiPlatformPkg/sun50iw1p1Pkg/sun50iw1p1Pkg.fdf
Processing meta-data ............. done!
Building ... /home/david/edk2/MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf [ARM]

"/home/david/edk2/SunxiPlatformPkg/pctools/toolchain/gcc-linaro/bin/arm-linux-gnueabi-gcc" -march=armv7-a -mfpu=neon -I/home/david/edk2/SunxiPlatformPkg/sun50iw1p1Pkg/Include/Sun50iW1P1 -g -O2 -fshort-wchar -fno-strict-aliasing -Wall -Werror -Wno-missing-braces -Wno-array-bounds -c -include AutoGen.h -mword-relocations -mlittle-endian -mabi=aapcs -mapcs -fno-short-enums -save-temps -fsigned-char -ffunction-sections -fdata-sections -fomit-frame-pointer -Wno-address -mfloat-abi=soft -fno-stack-protector -mno-unaligned-access -Wno-unused-but-set-variable -DCONFIG_ARCH_SUN50IW1P1 -o /home/david/edk2/Build/SunxiPlatform/sun50iw1p1Pkg/RELEASE_ARMLINUXGCC/ARM/MdePkg/Library/BasePcdLibNull/BasePcdLibNull/OUTPUT/./PcdLib.obj -I/home/david/edk2/MdePkg/Library/BasePcdLibNull -I/home/david/edk2/Build/SunxiPlatform/sun50iw1p1Pkg/RELEASE_ARMLINUXGCC/ARM/MdePkg/Library/BasePcdLibNull/BasePcdLibNull/DEBUG -I/home/david/edk2/MdePkg -I/home/david/edk2/MdePkg/Include -I/home/david/edk2/MdePkg/Include/Arm /home/david/edk2/MdePkg/Library/BasePcdLibNull/PcdLib.c

/bin/sh: 1: /home/david/edk2/SunxiPlatformPkg/pctools/toolchain/gcc-linaro/bin/arm-linux-gnueabi-gcc: not found

GNUmakefile:316: recipe for target '/home/david/edk2/Build/SunxiPlatform/sun50iw1p1Pkg/RELEASE_ARMLINUXGCC/ARM/MdePkg/Library/BasePcdLibNull/BasePcdLibNull/OUTPUT/PcdLib.obj' failed

make: *** [/home/david/edk2/Build/SunxiPlatform/sun50iw1p1Pkg/RELEASE_ARMLINUXGCC/ARM/MdePkg/Library/BasePcdLibNull/BasePcdLibNull/OUTPUT/PcdLib.obj] Error 127

build.py...
 : error 7000: Failed to execute command

 make --no-print-directory tbuild [/home/david/edk2/Build/SunxiPlatform/sun50iw1p1Pkg/RELEASE_ARMLINUXGCC/ARM/MdePkg/Library/BasePcdLibNull/BasePcdLibNull]

build.py...

 : error 7000: Failed to execute command

 make --no-print-directory tbuild [/home/david/edk2/Build/SunxiPlatform/sun50iw1p1Pkg/RELEASE_ARMLINUXGCC/ARM/MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull]

build.py...

 : error F002: Failed to build module

 /home/david/edk2/MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf [ARM, ARMLINUXGCC, RELEASE]

- Failed -

Build end time: 09:25:15, Jan.07 2017
Build total time: 00:00:14

I can not understand this error. the arm-linux-gnueabi-gcc is clearly in the pctools/toolchain directory and it has the executable attribute.

Any help?

**Comment by Leeway213** [comment]
Hi friend, sorry for late reply.
I have tried to build under ubuntu 16. This issue existed indeed.
I'm not sure what cause this problem yet, but you can try to install a new available arm-gcc binary in your OS and modify the path of ARMLINUXGCC_TOOLS_PATH in build.sh.

**Comment by MyPod** [comment]
The issue is that the toolchain is 32bit-based, while the OS is 64bit. You need to run the following commands to install the needed libraries:
`dpkg --add-architecture i386 && apt-get update`
`apt-get install libc6:i386 libstdc++6:i386 zlib1g:i386`
The toolchain will then work

**Comment by Leeway213** [comment]
got that! thank you!
